version: '3.9'

services:
  ju-shop:
    build:
      context: .
    container_name: ju-shop
    # environment:
    #   BASE_PATH: /shop
    #   ANALYTICS_ENABLED: "true"
    #   ANALYTICS_HOST: https://analytics.example.com
    #   ANALYTICS_SITE_ID: 00000000-0000-0000-0000-000000000000
    #   ANALYTICS_PROXY_ENABLED: "true"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.shop.rule=PathPrefix(`/shop`)"
    #   #- "traefik.http.middlewares.shop-strip.stripprefix.prefixes=/shop"
    #   #- "traefik.http.routers.shop.middlewares=shop-strip"
    #   - "traefik.http.services.shop.loadbalancer.server.port=80"
    ports:
      - "8087:80"

  # traefik:
  #   image: traefik:v2.10
  #   container_name: traefik
  #   command:
  #     - "--api.insecure=true"  # Optional: Expose Traefik's web UI (for debugging)
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Enable Docker provider
